Enable merging loads into  multi-csv files.
bigladder/erin pull request #63
Opened 2024-05-06 18:07 UTC by spahrenk

## Description of the Problem this PR will Solve

This PR provides the new CLI command "pack-loads". The full command syntax is:
`erin pack-loads <input.toml> --outcsv <default:packed-loads.csv>`

All loads in "input.toml" will be combined into a single csv file named packed-loads.csv, using the mutli-csv file format specified in the issue, with minor changes:
| tag-1 | size-1 | tag-2 | size-2 |
|--------|--------|--------|--------|
| seconds | W | seconds | W |
| 0 | 123.4 | 0 | 123.4 |
| 1 | 123.4 | 2 | 123.4 |
| 2 | 123.4 | 4 | 123.4 | 

This command does not change "input.toml" itself. Typically, the user will manually remove all existing single-load references in "input.toml" and, instead, enter only one entry of the form
```
[loads.combined_loads]
multi_part_csv = "packed-loads.csv"
```
(Note that the tag "combined_loads" is unused.)

The load parsing function was modified to prevent reading loads with duplicate names. (The name of a load read from a single-load file is the file name.) Therefore, it is not required to eliminate the single-load file references from "input.toml", though their removal will improve run times. (They can be deleted.) Also, this ensures that repeated calls to `erin pack-loads` will all produce the same output.

Loads can be distributed across multiple multi-load csv files, if desired, or some combination of single- and multi-load files.

Multi-load data is written as seconds/W, rather than hours/kW. A minor change was made that corrects truncation of power values during their assignment to unsigned integer variables. Regardless, some precision is lost during assignment of the original (double) power values to integers, which leads to diffs in the simulation results.

2024-05-06 19:01 UTC, spahrenk commented
Michael, please let me know what changes are needed here. Thx.

2024-05-06 19:26 UTC, michael-okeefe commented
Thanks @spahrenk . I'm excited to look at it but I've got a higher priority item I need to deal with first. I noticed that Github is saying this branch is out of date with the base `develop` branch. Could you update the branch when you have time?

2024-05-07 13:07 UTC, michael-okeefe commented on apps/erin.cpp
> +    {
I like how you put each subcommand in its own scope to prevent variable name clashes.

2024-05-07 15:00 UTC, michael-okeefe requested changes
Hi Phil,

Thank you for all of this work on this PR! This looks really great. However, we'll need to make a few changes prior to merging.

Firstly, the previous way that loads worked should continue to work after this PR is merged. My apologies if that wasn't clear. The reason we are making the "pack-loads" sub-command is to enable easy use of a multi-load csv feature but we don't want to take away the existing pathway. The "multi-load" csv will be a 3rd option for defining loads: the first is the in-line data -- see `docs/examples/ex01.toml` for instance; the second is our one file-per-load system; and the third is the multiple-loads per file system you're working on in this PR.

Related to the above point, we should definitely create a new example which showcases the multi-load functionality but we should keep the existing Ft Illinois example, as is. I would suggest we actually copy your current Ft Illinois example into a new folder called ft-illinois-packed and restore the previous ft-illinois input file. Among other things, this will allow us to profile the two versions side-by-side to show the speedup.

All of the regression tests will need to be able to run/pass before we can merge. You can run those via task by doing `task test`. I know you made that update to rounding (thank you for that) but it will probably slightly change results; the results should be reviewed and new regression data checked in as part of this PR although I'm happy to do that if you'd like. We might try running with and without the rounding just to be sure that regression changes are caused only by adding the load rounding -- if so, I think we can be more confident in checking in new regression results.

Secondly, I'd like to make some slight changes to what you're proposing for the input file. I hadn't actually realized you were already working on hooking up the input file side; that's great because that's where we're going so thank you for anticipating that but there are some additional considerations we need to accommodate.

I like your proposal to have a single point in the input file to load up all of the multiple loads from a single-file. However, as mentioned above, what we are doing is adding a new option as opposed to removing an existing option. For the current input file, loads are set up to be `[loads.user_gets_to_pick_this_name]`. As such, instead of nesting the multiple loads under the loads table, let's do this:

```
[multi_loads]
csv_file = "multiple_loads.csv"
```

If other `[loads.load_01]` objects show up in the input file, they should still be respected and loaded. However, we probably want to issue a warning if the same load tag is being loaded multiple times (I think issuing a warning and having "last man wins" is fine).

In the future, there is a "nice-to-have" objective to add meta-data to allow for one load to reference a subsection of another load and possibly have scaling (e.g., load_03 is equal to load_01 from August 1 at midnight for 14 days, scaled to 1.5 x normal value). We want to set ourselves up to be able to support that in the future as that may be a key way to send less data over the wire to ERIN and still accommodate scenario-based loads.

I'm happy to talk more off-line if anything is unclear. Please let me know if you have any questions, comments, or concerns.

2024-05-07 15:00 UTC, michael-okeefe commented on include/erin_next/erin_next_csv.h
> +
If we're going to move DoubleToString to erin_next_csv, then we should check if we need to still declare it in erin_next_simulation.h. If we do, we should clearly comment it as a forward declaration (perhaps move it to the top of the header file in a `// FORWARD DECLARATIONS` section or something).

2024-05-07 15:36 UTC, spahrenk commented on include/erin_next/erin_next_csv.h
> +
Looks like I missed that declaration in erin_next_simulation.h. I removed it and included erin_next_csv.h in a couple of files. Just thought it made more sense to have DoubleToString among other text utilities.

2024-05-07 16:41 UTC, spahrenk commented
Looks like I accidentally wiped out explicit load parsing, sorry. I will restore that. (I was focused on the ft-Illinois example, which seems to use csv only.)

2024-05-08 23:29 UTC, michael-okeefe approved these changes

2024-05-08 23:50 UTC, michael-okeefe commented
@spahrenk well, I was going to try and merge in develop and push it back up but something seems to have gone haywire with my clang-format... I just did a brew install locally which updated me to 18.1.5 but that doesn't seem to match what the CI is doing anymore. Could you just pull the code on your end, to `task format` and recommit and push? That should all pass and then we can merge. Meanwhile, I'll see if I can come up with a less fragile clang-format pathway...

2024-05-09 16:18 UTC, merged